name: Trigger auto deployment for treechat-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/treechat-frontend-AutoDeployTrigger.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TREECHATAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TREECHATAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TREECHATAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/apps/frontend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: treechat.azurecr.io
          registryUsername: ${{ secrets.TREECHATAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TREECHATAPI_REGISTRY_PASSWORD }}
          containerAppName: treechat-api
          resourceGroup: dev-no-iac
          imageToBuild: treechat.azurecr.io/treechat-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


